### ISSUE TITLE
Cooldown for commands

### ISSUE THREAD

**Issue by NotJustPizza** [Ne0nx3r0/BetterAlias#3]
I think, cooldown for commands is good idea. I know we can use 'wait' statement but it's only slowing down command.

Example usage:

``` yaml
kit:
  permission: kit
  cooldown: 60
  0:
    - console /give !name bread 10
    - console /give !name stone 10
spawn:
  permission: spawn
  cooldown: 10
  0:
    - console /tp !name 0 0 0
```
