### ISSUE TITLE
Random commands and options

### ISSUE THREAD

**Issue by NotJustPizza** [Ne0nx3r0/BetterAlias#4]
This idea will increase utility of plugin.

**Random options:**
!rnumber(0,100) - random number in 0-100
!rchar(8) - random word in a length of 8 characters
!rplayer - random name in online players

**Random commands and options in example usage:**

``` yaml
randomtp:
  permission: tp.random
  0:
    - console /tp !name !rnumber(-255,255) !rnumber(-255,255) !rnumber(-255,255)
    - reply &AQUAWooosh!
surprise:
  permission: donator.surprise
  0: "reply Usage: /suprise <username>"
  1:
    - random:    # define random commands
      - (10)console /give !1 diammond 1    # "(10)" is random command % chance
      - (20)console /give !1 apple 5    #20% chances
      - (69)console /give !1 stone 10    #69% chances
      - (1)console /pex user !1 group set vip   #1% chances
    - /msg !1 Suprise!
lottery:
  permission: admin.lottery
  0: "reply Usage: /lottery <item> <count>"
  1: /give !rplayer !1
  2: /give !rplayer !1 !2
```
